# Metadata about this component, to be used in the CMS
spec:
  structures:
    - left-right-hero
  label: "Left-right-hero-image"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image:
  image_alt:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  image: http://placekitten.com/200/200
  image_alt: A kitten
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
