# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Accordion Row"
  description:
  icon: table_rows
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: Staff
  accordion_item_groups: [bookshop:generic/accordion-item-group]
  _index: 
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Staff
  accordion_item_groups:
    - bookshop:generic/accordion-item-group
    - bookshop:generic/accordion-item-group
  _index: 1

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
