# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Space"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  size: 1
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  size: 1
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
size:
type: select
options:
  values:
    - half
    - 1
    - 2
    - 3