---
timezone: America/Chicago
baseurl: ""
include: ['_posts', '_data','login.html','login','_redirects']
relative_permalinks: false
# Your disqus shortname, entering this will enable commenting on posts
disqus: 
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-5620270-51
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'
# Permalinks
permalink: "/:title/"
main_content:
_inputs:
  main_content:
    type: markdown
    options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true 
      bulletedlist: true
      indent: true
      numberedlist: true
      outdent: true 
      code: true
      embed: true
      horizontalrule: true
      image: true
      table: true 
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      styles: /css/editor.css
      left: align-left
      center: align-center
      right: align-right
      justify: align-justify
bookshop_locations:
  - component-library
plugins:
  #- jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-bookshop
  - jekyll-redirect-from

# exclude:
  #   - .sass-cache/
  #   - .jekyll-cache/
  #   - gemfiles/
  #   - Gemfile
  #   - Gemfile.lock
  #   - node_modules/
  #   - vendor/bundle/
  #   - vendor/cache/
  #   - vendor/gems/
  #   - vendor/ruby/
  #   - _site