---
timezone: America/Chicago
baseurl: ""
include: ['_posts', '_data','login.html','login','_redirects']
relative_permalinks: false
# Your disqus shortname, entering this will enable commenting on posts
disqus: 
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# http://jekyllrb.com/docs/pagination/
defaults:
  - scope:
      type: pages
      path: ""
      layout: sub-page
paginate: 3
paginate_path: '/page:num/'
# Permalinks
permalink: "/:title/"
bookshop_locations:
  - component-library
plugins:
  #- jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-bookshop
  - jekyll-redirect-from

collections:
  posts:
    output: true



# exclude:
  #   - .sass-cache/
  #   - .jekyll-cache/
  #   - gemfiles/
  #   - Gemfile
  #   - Gemfile.lock
  #   - node_modules/
  #   - vendor/bundle/
  #   - vendor/cache/
  #   - vendor/gems/
  #   - vendor/ruby/
  #   - _site