source_editor:
# Base path to your site source files, same as source for Jekyll
source: site

# Populates collections for navigation and metadata in the editor
collections_config:
  people:
	# Base path for files in this collection, relative to source
	path: content/people

	# Whether this collection produces output files or not
	output: true

	# Collection-level configuration
	name: Personnel
	_enabled_editors:
	  - visual
	  - content
	  - data
  posts:
	path: _posts
	output: true
  pages:
	name: Main pages

paths:
  # The default location for newly uploaded files, relative to source
  uploads: assets/uploads

  # The path to the root collections folder, relative to source
  collections: items

  # The path to site data files, relative to source
  data: _data

  # The path to site layout files, relative to source
  layouts: _layouts

  # The path to site include files, relative to source
  includes: _includes