paths:
  uploads: "assets/img/:title"
  collections: items
  data: _data
  layouts: _layouts
  includes: _includes
source_editor:
  tab_size: 3
  theme: 'Accolades'
timezone: "America/Chicago"
_enabled_editors:
  - content
  - visual
  - data
_editables:
  text:
    italic: true
  block:
    format: p h3
    undo: true
    redo: true
  content:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    styles: /css/editor.css
    left: align-left
    center: align-center
    right: align-right
    justify: align-justify
    image_size_attributes: true
    snippet: true
data_config:
  home-banner: true
  homepage-notice: true
_inputs:
  Button_Positions:
    type: select
    options:
      values:
        - left
        - center
        - right
  Position:
    type: select
    options:
      values:
        - Below Image
        - Top Navigation
        - PopUp
  layout:
    type: select
    options:
      values:
        - default
        - sub-page