paths:
  uploads: "assets/img/:title"
  collections: items
  data: _data
  layouts: _layouts
  includes: _includes
source_editor:
  tab_size: 3
  theme: 'Accolades'
timezone: "America/Chicago"
_enabled_editors:
  - visual
  - content
  - data
 spare_parts:
    - Bolt
  _inputs:
    spare_part:
      type: multiselect
      options:
        values:
          - Bolt
          - Nut
          - Gear