# Populates collections for navigation and metadata in the editor
collections_config:
	# Collection-level configuration
  _enabled_editors:
    - visual
    - content
    - data
  posts:
  path: _posts
  output: true
paths:
  # The default location for newly uploaded files, relative to source
  uploads: assets/img
  # The path to site data files, relative to source
  data: _data
  # The path to site layout files, relative to source
  layouts: _layouts
  # The path to site include files, relative to source
  includes: _includes