paths:
  uploads: "assets/img/:title"
  collections: items
  data: _data
  layouts: _layouts
  includes: _includes
source_editor:
  tab_size: 3
  theme: 'Accolades'
timezone: "America/Chicago"
_enabled_editors:
  - content
  - visual
  - data
_editables:
  block:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    code: true
    embed: true
    image: true
    table: true
    left: align-left
    center: align-center
    right: align-right
  content:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    code: true
    embed: true
    image: true
    table: true
    left: align-left
    center: align-center
    right: align-right
data_config:
  home-banner: true
  homepage-notice: true
_inputs:
  Button_Positions:
    type: select
    options:
      values:
        - left
        - center
        - right
  Position:
    type: select
    options:
      values:
        - Below Image
        - Top Navigation
        - PopUp
  layout:
    type: select
    options:
      values:
        - sub-page
        - default
collections_config:
  pages:
    create:
      path: '[relative_base_path]/{title|slugify}.html'