paths:
  uploads: 'assets/img/:title'
  collections: items
  data: _data
  layouts: _layouts
  includes: _includes
source_editor:
  tab_size: 3
  theme: 'Accolades'
timezone: 'America/Chicago'
_editables:
  block:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    code: true
    embed: true
    image: true
    table: true
    styles: /assets/css/theme.css
    left: text-left
    center: text-center
    right: text-right
    image_size_attributes: false
    expandable: true
  content:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    code: true
    embed: true
    image: true
    table: true
    redo: true 
    image_size_attributes: false
    expandable: true
    removeformat: true
    copyformatting: true 
    styles: /assets/css/theme.css
    left: text-left
    center: text-center
    right: text-right
collections_config:
  pages:
    schemas:
      block_page:
        path: schemas/page.md
        _enabled_editors:
          - visual
          - content
      content_page:
        path: schemas/content-page.md
        _enabled_editors:
          - content
          - visual
data_config:
  home-banner: true
  homepage-notice: true
  navigation: true
  posts: true
_inputs:
  Button_Positions:
    type: select
    options:
      values:
        - left
        - center
        - right
  Location:
    type: select
    options:
      values:
        - Below Image
        - Top Navigation
        - PopUp
  layout:
    type: select
    options:
      values:
        - sub-page
        - default
        - content-page

_structures:
  content_blocks:
    style: 'modal'
  left-right-hero:
    style: 'select'
