paths:
  uploads: "assets/img/:title"
  collections: items
  data: _data
  layouts: _layouts
  includes: _includes
source_editor:
  tab_size: 3
  theme: 'Accolades'
timezone: "America/Chicago"
_enabled_editors:
  - visual
  - content
  - data
data_config:
  Button-Position:
    type: select
    options:
      values: left
      values: center
      value: right