paths:
  uploads: "assets/img/:title"
  collections: items
  data: _data
  layouts: _layouts
  includes: _includes
source_editor:
  tab_size: 3
  theme: 'Accolades'
timezone: "America/Chicago"
_enabled_editors:
  - content
  - visual
  - data
_editables:
  content:
    bold: true
    italic: true
    bulletlist: true
    numberedlist: true
    image: true
    table: true
    undo: true
    redo: true
    left: align-left
    center: align-center
    right: align-right
data_config:
  home-banner: true
  homepage-notice: true
_inputs:
  Button_Positions:
    type: select
    options:
      values:
        - left
        - center
        - right
  Position:
    type: select
    options:
      values:
        - Below Image
        - Top Navigation
        - PopUp
  layout:
    type: select
    options:
      values:
        - default
        - sub-page