# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Button-link"
  description: 
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: 
  url: 
  external_url: false
  color_variation: 
  animate_hover: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: Button text
  url: /
  external_url: false
  color_variation: green
  animate_hover: false

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  color_variation:
    type: select
    options:
      values:
        - blue
        - green
    comment: Color options for the button
  animate_hover:
    comment: Add a hover animation on the button
  text:
    comment: Text inside the button
  url:
    comment: URL address the button links to 
  external_url: 
    type: checkbox
