# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: 'Why were here section group item'
  description: Why were here section group item with black title with image
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: 
  text:
  image:
    src: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Lorem ipsum dolor sit amet
  text:
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
  image:
    src: https://dummyimage.com/748x499/000/e0e0e0

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    label: Title
    comment: Section Title
    type: text
  text:
    label: Text
    comment: The text content of the section.
    type: markdown
  src:
    label: Image Source
    comment: The address of the image to be displayed.
    type: url
