# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Become-a-partner-section"
  description: Become a partner block. Includes a signup form
  icon: crop_7_5
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  body_text: 
  extra_space_top: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  body_text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis lectus elit. Vivamus posuere quam vestibulum enim sodales semper. Pellentesque euismod elit non pulvinar tincidunt
  extra_space_top: true

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  extra_space_top:
    type: checkbox
    comment: Toggle extra space above the component
  
