# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "left-right-section-text"
  description: Left Right Text blocks - Two column of text with titles
  icon: label
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  left:
    post_link_text: 
    left_title: 
  right:
    right_title: 
    card_title: 
    text:
    image:
    url:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  left:
    post_link_text: Visit Newsroom
    left_title: LATEST NEWS
  right:
    right_title: HOT SPOT 
    card_title: The Flu is Back in Texas
    text: >-
      The influenza epidemic is sending people to hospitals in every region of the
      state, resulting in few available beds - and increasing hospital staff
      shortages.

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
