# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Code block"
  description: "This is used to embed code"
  icon: barcode
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
 code_block: >-
   

# Overrides any fields in the blueprint when viewing this component in the component browser
code_block: >-

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  code_block:
    comment: Code wont render in page preview