# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Carousel"
  description: 
  icon: view_carousel
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  cards: [bookshop:simple/carousel-card]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  cards:
    - bookshop:simple/carousel-card
    - bookshop:simple/carousel-card
    - bookshop:simple/carousel-card

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
