# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Why were here section group"
  description: Left right content section with a gap in between each text/image.
  icon: vertical_split
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  left_right: [bookshop:simple/left-right-image-with-gap]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  left_right: 
    - bookshop:simple/left-right-image-with-gap
    - bookshop:simple/left-right-image-with-gap
    - bookshop:simple/left-right-image-with-gap

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
