# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Card-section"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: 
  subtitle: 
  cards: [bookshop:simple/info-card]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: We're a voice for Texans who want to prevent disease
  subtitle: We connect, educate, and advocate to ensure access to vaccines and increase immunization.
  cards:
    - bookshop:simple/info-card
    - bookshop:simple/info-card
    - bookshop:simple/info-card

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
