# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Our Partners Diagram"
  description: Interactive diagram of partners 
  icon: panorama_fish_eye
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    hidden: true
