# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "News-list-item"
  description: News item component
  icon: newspaper
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  post:
    url:
    title:
    source:
    date:
    content: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
