# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Accordion Item"
  description: Expanable Section used on staff
  icon: tab_unselected
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  type: staff 
  image:
  name:
  position:
  title:
  url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  type: staff 
  image: https://dummyimage.com/436x550/000/e0e0e0
  name: Name
  position: Position
  title: Title
  url: ""

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  type:
    label: Item Type
    comment: Pick the appropriate type of accordion item for their relevant styles.
    type: select
    options:
      values:
        - staff
        - director
        - scientific-advisory
        - job-listing

