# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Text Section"
  description: A text section with heading, with optional centering.
  icon: notes
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: 
  text: 
  centered: false
  colored_background: false
  no_title: false
  no_paragraph: false
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: "Title Text"
  text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam."
  centered: false
  colored_background: false
  no_title: false
  no_paragraph: false
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    label: Title
    comment: The title used as the heading for this section.
    type: Rich text
  text:
    label: Text
    comment: "The text content of this section."
    type: markdown
  centered:
    label: Center Text
    comment: Select true to center text in this section.
    type: switch
  colored_background:
    label: Colored Background
    comment: Select true for a colored background.
    type: switch
  no_title:
    label: Disable Title
    comment: Select true to remove title.
    type: switch
  no_paragraph:
    label: Disable Paragraph
    comment: Select true to remove paragraph.
    type: switch
