# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Text-section"
  description: A text section with heading, with optional centering.
  icon: notes
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: 
  text: 
  centered: false
  colored_background: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: "Our Partners"
  text: "The Immunization Partnership earned its place as THE credible resource on immunization in Texas because of our access to a unique network we maintain consisting of experts in public health and public policy, as well as leaders in medicine (both practitioners and researchers) communications, education, and health care administration."
  centered: false
  colored_background: false

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    label: Title
    comment: The title used as the heading for this section.
    type: text
  text:
    label: Text
    comment: "The text content of this section."
    type: markdown
  centered:
    label: Center Text
    comment: Select true to center text in this section.
    type: switch
  colored_background:
    label: Colored Background
    comment: Select true for a colored background.
    type: switch
