# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Background-image-section"
  description: Full width section with a background image
  icon: crop_7_5
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: 
  image: 
  button: bookshop:generic/button-link
  space-top: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: Texas strength depends on the health of its citizens. We advocate everyday to keep Texas strong. 
  image: /assets/img/the-immunization-partnership/day-7-photography-47-2.jpg?_cchid=d79a95f68129ecdd6cb6ed27b53468b7
  button: bookshop:generic/button-link
  space-top: false

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: textarea
  image:
    comment: The background image for the section
  button:
    comment: Optioanl button beneath the text
  space-top:
    type: checkbox
    comment: toggle extra space above the component