# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Background image with text"
  description: Full width section with a background image text and a button
  icon: crop_7_5
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt 
  image: https://dummyimage.com/1620x1080/000/e0e0e0
  contain: false
  colored_background: false
  background_color: '#fff'
  button: bookshop:generic/button-link
  space-top: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt 
  image: https://dummyimage.com/1620x1080/000/e0e0e0
  contain: false
  colored_background: false
  background_color: '#fff'
  button: bookshop:generic/button-link
  space-top: false
  disable-button: false
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: textarea
  image:
    comment: The background image for the section
  contain:
    label: Contain Image
    comment: Select true to maintain image in section
    type: switch
  colored_background:
    label: Colored Background
    comment: Select true if you want a color background to blend in with image.
    type: switch
  background_color: 
    label: Background Color Picker 
    comment: Use to select background color
    type: color
  button:
    comment: Optioanl button beneath the text
  space-top:
    type: checkbox
    comment: toggle extra space above the component
  disable-button:
    type: checkbox
    comment: toggle to turn off button
 