# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Background image with text"
  description: Full width section with a background image text and a button
  icon: crop_7_5
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt 
  image: https://dummyimage.com/1620x1080/000/e0e0e0
  button: bookshop:generic/button-link
  space-top: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt 
  image: https://dummyimage.com/1620x1080/000/e0e0e0
  button: bookshop:generic/button-link
  space-top: false
  disable-button: false
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: textarea
  image:
    comment: The background image for the section
  button:
    comment: Optioanl button beneath the text
  space-top:
    type: checkbox
    comment: toggle extra space above the component
  disable-button:
    type: checkbox
    comment: toggle to turn off button