# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Left Card with Image"
  description: Left right section displaying a card, on the left image on the right. 
  icon: label
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  left_section:
    title:
    text: 
    colored_background: true
    bold_title: false
  right_section: bookshop:structure:left-right-hero
      
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  left_section:
    title: Lorem ipsum
    text: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
    colored_background: true
    bold_title: false
  right_section: bookshop:generic/left-right-hero-image
    
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    label: Title
    comment: The card title.
    type: text
  text:
    label: Text
    comment: The text content of the card.
    type: markdown
  colored_background:
    label: Shaded Background
    comment: Select true to make the background color of the card blue.
    type: switch
  bold_title:
    label: Bold Title
    comment: Select true to make the title bold.
    type: switch
