# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Left-right-hero"
  description: Left-Right section displaying a card, on the left. 
  icon: label
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  left_section:
    title:
    text: 
    colored_background: true
    bold_title: false
  right_section: bookshop:structure:left-right-hero
      
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  left_section:
    title: Why We're Here
    text: Despite having vaccines that prevent more than 20 life-threatening diseases, those diseases have not gone away. The number of people receiving routine vaccinations has dropped for the first time in a decade. Texas is ground-zero for the anti-vaccination movement, putting our children and our communities at great risk for disease outbreaks, such as measles and chicken pox.&nbsp;<br /><br />More Texas families are opting their children out from one or more school required vaccines, leading to an increase in vaccine exemptions.
    colored_background: true
    bold_title: false
  right_section: bookshop:generic/left-right-hero-image
    
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    label: Title
    comment: The card title.
    type: text
  text:
    label: Text
    comment: The text content of the card.
    type: markdown
  colored_background:
    label: Shaded Background
    comment: Select true to make the background color of the card blue.
    type: switch
  bold_title:
    label: Bold Title
    comment: Select true to make the title bold.
    type: switch
