# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Info-card"
  description: A simple informational card with button and image. 
  icon: call_to_action
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: The overload of information, and misinformation, about vaccines requires insight from a qualified network of scientific experts.
  image:
    src: https://dummyimage.com/348x232/000/e0e0e0
    alt: 
    width: 100%
  button: bookshop:generic/button-link

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: The overload of information, and misinformation, about vaccines requires insight from a qualified network of scientific experts.
  image:
    src: https://dummyimage.com/348x232/000/e0e0e0
    alt: Image Description
    width: 100%
  button: bookshop:generic/button-link

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    label: Text
    comment: The text content of the card.
    type: markdown
  src:
    label: Src
    comment: The path to the image.
    type: url
  alt:
    label: Image Alt
    comment: A description of the image.
    type: text
  width:
    label: Width
    comment: The width of the image.
    type: number

