# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero-banner-image"
  description: Full width banner image. Intended for top of pages. 
  icon: panorama
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  image: https://placebear.com/2000/500

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
