# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero banner"
  description: Full width banner image. Intended for top of pages. 
  icon: panorama
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image: https://dummyimage.com/1620x1080/000/e0e0e0

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  image: https://dummyimage.com/1620x1080/000/e0e0e0

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
