# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: 'Left Right Card Group Item'
  description: Fills left right group
  icon: vertical_split
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: 
  text: 
  button: bookshop:generic/button-link
  image: 
  flipped: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Lorem ipsum dolor sit amet, consectetur 
  text: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
  button: bookshop:generic/button-link
  image: https://dummyimage.com/570x503/000/e0e0e0
  flipped: false

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
