# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Left-right-group"
  description: A wrapper for left-right-group-items
  icon: vertical_split
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  blocks: [bookshop:simple/left-right-group-item]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  blocks:
    - bookshop:simple/left-right-group-item
    - bookshop:simple/left-right-group-item
    - bookshop:simple/left-right-group-item

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
